<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Version>0.4.0</Version></PropertyGroup>
  <ItemGroup>
    <Reference Include="OpenMetaverse"><HintPath>$(OpenSimBin)/OpenMetaverse.dll</HintPath></Reference>
    <Reference Include="OpenMetaverseTypes"><HintPath>$(OpenSimBin)/OpenMetaverseTypes.dll</HintPath></Reference>
    <Reference Include="OpenMetaverse.StructuredData"><HintPath>$(OpenSimBin)/OpenMetaverse.StructuredData.dll</HintPath></Reference>
    <Reference Include="log4net"><HintPath>$(OpenSimBin)/log4net.dll</HintPath></Reference>
    <Reference Include="zlib.net"><HintPath>$(OpenSimBin)/zlib.net.dll</HintPath></Reference>
    <Reference Include="XMLRPC"><HintPath>$(OpenSimBin)/XMLRPC.dll</HintPath></Reference>
    <Reference Include="SmartThreadPool"><HintPath>$(OpenSimBin)/SmartThreadPool.dll</HintPath></Reference>
    <Reference Include="System.Configuration.ConfigurationManager"><HintPath>$(OpenSimBin)/System.Configuration.ConfigurationManager.dll</HintPath></Reference>
  </ItemGroup>
</Project>
